require("sahil.plugins")
require("sahil.options")
require("sahil.keybindings")
require("sahil.autopairs")
require("sahil.comment")
require("sahil.bufferline")
require("sahil.impatient")
require("sahil.lualine")
